### ISSUE TITLE
replace ngmin and add htmlmin

### ISSUE THREAD

**Issue by PhilFlash** [lauterry/generator-ngtailor#7]
Hi,
Replace ngmin by ngAnnotate (ngmin is deprecated).
Add htmlmin to Grunt.js like this:
		htmlmin: {
		   dist: {
			 options: {
			   collapseWhitespace: true,
			   conservativeCollapse: true,
			   collapseBooleanAttributes: true,
			   removeComments: true,
			   removeCommentsFromCDATA: true,
			   removeOptionalTags: true
			 },
			 files: [{
			   expand: true,
			   cwd: '<%= distDir %>',
			   src: ['index.html', 
                                          // 'views/{,*/}*.html'
                                    ],
			   dest: '<%= distDir %>'
			 }]
		   }
		},
...
    grunt.registerTask('package', [
        'jshint',
        'clean',
        'useminPrepare',
        'copy',
        'concat',
        'ngmin',
        'uglify',
        'less',
        'cssmin',
        'rev',
        'usemin',
        'htmlmin'
    ]);
Philippe

**Comment by lauterry** [comment]
Hello Phillipe

Thanks for the issue.

ngAnnotate and htmlmin have been integrated in 96f05a9639a2e7c0b525274fa34eb259554de72f and 831b1a33ef9b153a58531117661f3ce09a653915

Best regards
